const EGGS = [
  {
    id: "vanilla-java",
    name: "Minecraft Java — Vanilla",
    short: "Resmi vanilla Java sunucusu",
    game: "Minecraft Java",
    category: "java",
    icon: "cube",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M -jar server.jar nogui",
    stop: "stop",
    defaultPort: 25565,
    protocol: "java",
    files: {
      "eula.txt": "eula=true\n",
      "server.properties": [
        "server-port={{SERVER_PORT}}",
        "motd=HoptoNode Vanilla",
        "online-mode=true",
        "max-players={{MAX_PLAYERS}}",
        "difficulty=normal",
        "view-distance=10",
        "simulation-distance=8",
        "white-list=false",
        "enable-command-block=true",
        "spawn-protection=0",
      ].join("\n") + "\n",
    },
    variables: [
      { key: "MC_VERSION", name: "Sürüm", default: "1.21.4", description: "Minecraft Java sürümü" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "20" },
    ],
    notes: "İlk açılışta resmi server.jar indirilir (lisans: Mojang EULA).",
  },
  {
    id: "paper",
    name: "Paper",
    short: "Yüksek performanslı Java (Spigot uyumlu eklentiler)",
    game: "Minecraft Java",
    category: "java",
    icon: "paper",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M -jar server.jar nogui",
    stop: "stop",
    defaultPort: 25565,
    protocol: "java",
    files: {
      "eula.txt": "eula=true\n",
      "server.properties": "server-port={{SERVER_PORT}}\nmotd=HoptoNode Paper\nmax-players={{MAX_PLAYERS}}\nonline-mode=true\n",
    },
    variables: [
      { key: "MC_VERSION", name: "Sürüm", default: "1.21.4" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "40" },
    ],
    notes: "Paper, eklenti ekosistemi için önerilen çekirdek.",
  },
  {
    id: "fabric",
    name: "Fabric",
    short: "Hafif mod yükleyici — Fabric API",
    game: "Minecraft Java",
    category: "modded",
    icon: "fabric",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M -jar fabric-server-launch.jar nogui",
    stop: "stop",
    defaultPort: 25565,
    protocol: "java",
    files: {
      "eula.txt": "eula=true\n",
      "server.properties": "server-port={{SERVER_PORT}}\nmotd=HoptoNode Fabric\nmax-players={{MAX_PLAYERS}}\n",
    },
    variables: [
      { key: "MC_VERSION", name: "Minecraft sürümü", default: "1.21.4" },
      { key: "LOADER_VERSION", name: "Fabric Loader", default: "0.16.10" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "20" },
    ],
    notes: "mods/ klasörüne .jar bırakın. Fabric API önerilir.",
  },
  {
    id: "forge",
    name: "Forge",
    short: "Klasik mod ekosistemi",
    game: "Minecraft Java",
    category: "modded",
    icon: "forge",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M @libraries/net/minecraftforge/forge/{{MC_VERSION}}-{{FORGE_VERSION}}/unix_args.txt nogui",
    stop: "stop",
    defaultPort: 25565,
    protocol: "java",
    files: {
      "eula.txt": "eula=true\n",
      "server.properties": "server-port={{SERVER_PORT}}\nmotd=HoptoNode Forge\nmax-players={{MAX_PLAYERS}}\n",
    },
    variables: [
      { key: "MC_VERSION", name: "Minecraft sürümü", default: "1.20.1" },
      { key: "FORGE_VERSION", name: "Forge sürümü", default: "47.3.0" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "20" },
    ],
    notes: "mods/ klasörüne Forge modlarını koyun.",
  },
  {
    id: "neoforge",
    name: "NeoForge",
    short: "Forge'un modern çatalı",
    game: "Minecraft Java",
    category: "modded",
    icon: "neoforge",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M @unix_args.txt nogui",
    stop: "stop",
    defaultPort: 25565,
    protocol: "java",
    files: {
      "eula.txt": "eula=true\n",
      "server.properties": "server-port={{SERVER_PORT}}\nmotd=HoptoNode NeoForge\nmax-players={{MAX_PLAYERS}}\n",
    },
    variables: [
      { key: "MC_VERSION", name: "Minecraft sürümü", default: "1.21.1" },
      { key: "NEOFORGE_VERSION", name: "NeoForge sürümü", default: "21.1.93" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "20" },
    ],
    notes: "Yeni nesil Forge modları için.",
  },
  {
    id: "quilt",
    name: "Quilt",
    short: "Fabric uyumlu alternatif yükleyici",
    game: "Minecraft Java",
    category: "modded",
    icon: "quilt",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M -jar quilt-server-launch.jar nogui",
    stop: "stop",
    defaultPort: 25565,
    protocol: "java",
    files: {
      "eula.txt": "eula=true\n",
      "server.properties": "server-port={{SERVER_PORT}}\nmotd=HoptoNode Quilt\nmax-players={{MAX_PLAYERS}}\n",
    },
    variables: [
      { key: "MC_VERSION", name: "Minecraft sürümü", default: "1.21.4" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "20" },
    ],
  },
  {
    id: "bedrock",
    name: "Minecraft Bedrock Dedicated",
    short: "Resmi Bedrock (Windows / konsol / mobil)",
    game: "Minecraft Bedrock",
    category: "bedrock",
    icon: "bedrock",
    dockerImage: "ubuntu:24.04",
    startup: "LD_LIBRARY_PATH=. ./bedrock_server",
    stop: "stop",
    defaultPort: 19132,
    protocol: "bedrock",
    files: {
      "server.properties": [
        "server-name=HoptoNode Bedrock",
        "server-port={{SERVER_PORT}}",
        "server-portv6={{SERVER_PORT}}",
        "max-players={{MAX_PLAYERS}}",
        "gamemode=survival",
        "difficulty=normal",
        "allow-cheats=false",
        "online-mode=true",
        "view-distance=12",
        "level-name=Bedrock",
      ].join("\n") + "\n",
    },
    variables: [
      { key: "BDX_VERSION", name: "Bedrock sürümü", default: "latest" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "20" },
    ],
    notes: "UDP 19132. Microsoft EULA geçerlidir.",
  },
  {
    id: "pocketmine",
    name: "PocketMine-MP",
    short: "PHP tabanlı Bedrock / PE sunucusu",
    game: "Minecraft Bedrock",
    category: "bedrock",
    icon: "pmmp",
    dockerImage: "pmmp/pocketmine-mp:latest",
    startup: "./bin/php7/bin/php PocketMine-MP.phar --no-wizard --disable-ansi",
    stop: "stop",
    defaultPort: 19132,
    protocol: "bedrock",
    files: {
      "server.properties": [
        "server-name=HoptoNode PocketMine",
        "server-port={{SERVER_PORT}}",
        "max-players={{MAX_PLAYERS}}",
        "gamemode=survival",
        "difficulty=2",
        "white-list=off",
        "xbox-auth=on",
        "language=tur",
      ].join("\n") + "\n",
    },
    variables: [
      { key: "PM_VERSION", name: "PMMP sürümü", default: "5.28.2" },
      { key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "30" },
    ],
    notes: "plugins/ klasörüne .phar eklenti bırakın.",
  },
  {
    id: "nukkit",
    name: "NukkitX",
    short: "Java ile Bedrock sunucusu",
    game: "Minecraft Bedrock",
    category: "bedrock",
    icon: "nukkit",
    dockerImage: "eclipse-temurin:21-jre",
    startup: "java -Xms{{MIN_MEMORY}}M -Xmx{{MEMORY}}M -jar nukkit.jar",
    stop: "stop",
    defaultPort: 19132,
    protocol: "bedrock",
    files: {
      "nukkit.yml": "settings:\n  language: tur\n",
    },
    variables: [{ key: "MAX_PLAYERS", name: "Maks. oyuncu", default: "30" }],
  },
];

function getEgg(id) {
  return EGGS.find((e) => e.id === id) || null;
}

module.exports = { EGGS, getEgg };
